FROM httpd:latest

COPY Docker/Dockerfile/Dev/httpd-vhosts.conf /usr/local/apache2/conf/extra/httpd-vhosts.conf

RUN echo "Include conf/extra/httpd-vhosts.conf" \
    >> /usr/local/apache2/conf/httpd.conf

EXPOSE 80
